### ISSUE TITLE
What is the best repo to fork for adding new device ?

### ISSUE THREAD

**Issue by hyviquel** [clang-ykt/openmp#1]
Hi all,
I'm looking for your advices: I do not have any issue 😉 
I implemented an [extension](https://github.com/ompcloud/libomptarget) of libomptarget for the cloud using [the first implementation](https://github.com/clang-omp/libomptarget).
Now, I would like to update my code to the last implementation but I not sure from which repository I should start. Do you think I should use this repository or the official LLVM repo that already contains some ?
I'm asking your opinion because there is still some differences (for example there is no DevRTLs yet on llvm repository) and I do not know all the differences so I'm not sure what would be the best move for me. 
Thanks,
Hervé

**Comment by carlobertolli** [comment]
Hi

Indeed, the trunk is still missing DevRTLs and most of code generation of OpenMP device constructs for NVIDIA GPUs.

That said, it is up to you to decide how much you need of code generation. I do not think Libomptarget DevRTLs should not be far away from being upstreamed. If you can wait a little more and you do not need GPU-related code generation, then you can probably work directly in the trunk. 
If, otherwise, you rely a lot on GPU code generation, then you are probably better off working with clang-ykt.

Thanks!

**Comment by hyviquel** [comment]
ok thanks
