### ISSUE TITLE
Compile LIBOMPTARGET for multiple Compute Capability

### ISSUE THREAD

**Issue by simoatze** [clang-ykt/openmp#7]
Hi,

I am trying to compile the OpenMP runtime for both Compute Capabiluty 35 and 60. This is my cmake command:

cmake -DCMAKE_BUILD_TYPE=DEBUG \
    -G Ninja \
    -D CMAKE_INSTALL_PREFIX=$HOME/usr_linux86-64 \
    -D BUILD_SHARED_LIBS=OFF \
    -D OPENMP_ENABLE_LIBOMPTARGET=ON \
    -D CMAKE_C_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=35,60' \
    -D CMAKE_CXX_FLAGS='-DOPENMP_NVPTX_COMPUTE_CAPABILITY=35,60' \
    -D LIBOMPTARGET_NVPTX_ENABLE_BCLIB=true \
    -D LIBOMPTARGET_DEP_LIBELF_INCLUDE_DIR=$HOME/usr_linux86-64/include \
    -D LIBOMPTARGET_DEP_LIBFFI_INCLUDE_DIR=$HOME/usr_linux86-64/lib/libffi-3.2.1/include \
    ..

However of I compile and run my program in a machine with a GPU with CC:60 it does not run in the device.

If I run the clang command with -v I can see that nvlink is called with "-arch sm_35" and I believe that that comes from the fact that I compiled clang with the flag "-D CLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_35".
Is there a way to compile the library such that it works fortwo devices with different compute capability?

Thanks.
Simone

**Comment by doru1004** [comment]
Did you use the -Xopenmp-target -march=sm_60 when compiling your program? That should overwrite the sm_35 default which you set via cmake. The problem is that even after you do that you will not get the inlining due to the BCLIB not having been compiled with the appropriate compute capability.

At the moment some changes to the libomptarget cmake are required for the compilation of multiple bclibs to work properly. Some changes to the CLANG driver are also necessary. I have the patches but they are not in the clang-ykt master branch yet.

**Comment by simoatze** [comment]
@doru1004 That was the flag I was missing thanks.
I think for now is enough, I was able to use the same library with two GPUs with different capabilities.
